DISTNAME=       my-mail-tools-1.0
CATEGORIES=     meta-pkgs my-mail-tools-1.0
MASTER_SITES=   # empty
DISTFILES=      # empty

MAINTAINER=     Marko Bauhardt
HOMEPAGE=       https://bauhardt.com
COMMENT=        My mail tools of choice

DEPENDS+=       mblaze-[0-9]*:../../mail/mblaze
DEPENDS+=       mu-[0-9]*:../../wip/mu

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
