DISTNAME=       my-security-tools-1.0
CATEGORIES=     meta-pkgs my-security-tools-1.0
MASTER_SITES=   # empty
DISTFILES=      # empty

MAINTAINER=     Marko Bauhardt
HOMEPAGE=       https://bauhardt.com
COMMENT=        My sec tools of choice

DEPENDS+=       age-[0-9]*:../../security/age
DEPENDS+=       minisign-[0-9]*:../../security/minisign

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
