DISTNAME=       my-editors-1.0
CATEGORIES=     meta-pkgs my-editors
MASTER_SITES=   # empty
DISTFILES=      # empty

MAINTAINER=     Marko Bauhardt
HOMEPAGE=       https://bauhardt.com
COMMENT=        My editors of choice

DEPENDS+=       vis-editor-[0-9]*:../../wip/vis-editor
DEPENDS+=       emacs29-nox11-[0-9]*:../../editors/emacs29-nox11
DEPENDS+=       ledger-[0-9]*:../../finance/ledger
META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
