DISTNAME=       my-baseline-1.0
CATEGORIES=     meta-pkgs my-baseline
MASTER_SITES=   # empty
DISTFILES=      # empty

MAINTAINER=     Marko Bauhardt
HOMEPAGE=       https://bauhardt.com
COMMENT=        Baseline utilitiies, mostly shell related things

DEPENDS+=       mksh-[0-9]*:../../shells/mksh
DEPENDS+=       colorit-[0-9]*:../../textproc/colorit
DEPENDS+=       fd-find-[0-9]*:../../sysutils/fd-find
DEPENDS+=       ripgrep-[0-9]*:../../textproc/ripgrep
DEPENDS+=       fzy-[0-9]*:../../misc/fzy
DEPENDS+=       stow-[0-9]*:../../sysutils/stow

META_PACKAGE=   yes

.include "../../mk/bsd.pkg.mk"
